sudo: required

services:
  - docker

before_script:
  - sudo service docker stop
  - if [ "$(ls -A /home/travis/docker)" ]; then echo "/home/travis/docker already set"; else sudo mv /var/lib/docker /home/travis/docker; fi
  - sudo bash -c "echo 'DOCKER_OPTS=\"-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -g /home/travis/docker\"' > /etc/default/docker"
  - sudo service docker start
  - docker build build-container -t griddle-build
  
script:
  - docker run -v $(pwd):/src/griddle -ti griddle-build build

before_cache:
  - docker rmi -f $(docker images | grep "<none>" | awk "{print \$3}")
  - sudo service docker stop
  - sudo chown -R travis ~/docker

cache:
  directories:
    ~/docker
